// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: dao.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DaoByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DaoId         string                 `protobuf:"bytes,1,opt,name=dao_id,json=daoId,proto3" json:"dao_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaoByIDRequest) Reset() {
	*x = DaoByIDRequest{}
	mi := &file_dao_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaoByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaoByIDRequest) ProtoMessage() {}

func (x *DaoByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dao_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaoByIDRequest.ProtoReflect.Descriptor instead.
func (*DaoByIDRequest) Descriptor() ([]byte, []int) {
	return file_dao_proto_rawDescGZIP(), []int{0}
}

func (x *DaoByIDRequest) GetDaoId() string {
	if x != nil {
		return x.DaoId
	}
	return ""
}

type DaoInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Name            string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Avatar          string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Alias           string                 `protobuf:"bytes,6,opt,name=alias,proto3" json:"alias,omitempty"`
	Verified        bool                   `protobuf:"varint,7,opt,name=verified,proto3" json:"verified,omitempty"`
	PopularityIndex float64                `protobuf:"fixed64,8,opt,name=popularity_index,json=popularityIndex,proto3" json:"popularity_index,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DaoInfo) Reset() {
	*x = DaoInfo{}
	mi := &file_dao_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaoInfo) ProtoMessage() {}

func (x *DaoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dao_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaoInfo.ProtoReflect.Descriptor instead.
func (*DaoInfo) Descriptor() ([]byte, []int) {
	return file_dao_proto_rawDescGZIP(), []int{1}
}

func (x *DaoInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DaoInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DaoInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *DaoInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DaoInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *DaoInfo) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *DaoInfo) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *DaoInfo) GetPopularityIndex() float64 {
	if x != nil {
		return x.PopularityIndex
	}
	return 0
}

type DaoByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dao           *DaoInfo               `protobuf:"bytes,1,opt,name=dao,proto3" json:"dao,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaoByIDResponse) Reset() {
	*x = DaoByIDResponse{}
	mi := &file_dao_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaoByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaoByIDResponse) ProtoMessage() {}

func (x *DaoByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dao_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaoByIDResponse.ProtoReflect.Descriptor instead.
func (*DaoByIDResponse) Descriptor() ([]byte, []int) {
	return file_dao_proto_rawDescGZIP(), []int{2}
}

func (x *DaoByIDResponse) GetDao() *DaoInfo {
	if x != nil {
		return x.Dao
	}
	return nil
}

var File_dao_proto protoreflect.FileDescriptor

const file_dao_proto_rawDesc = "" +
	"\n" +
	"\tdao.proto\x12\astorage\x1a\x1fgoogle/protobuf/timestamp.proto\"'\n" +
	"\x0eDaoByIDRequest\x12\x15\n" +
	"\x06dao_id\x18\x01 \x01(\tR\x05daoId\"\x98\x02\n" +
	"\aDaoInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05alias\x18\x06 \x01(\tR\x05alias\x12\x1a\n" +
	"\bverified\x18\a \x01(\bR\bverified\x12)\n" +
	"\x10popularity_index\x18\b \x01(\x01R\x0fpopularityIndex\"5\n" +
	"\x0fDaoByIDResponse\x12\"\n" +
	"\x03dao\x18\x01 \x01(\v2\x10.storage.DaoInfoR\x03dao2C\n" +
	"\x03Dao\x12<\n" +
	"\aGetByID\x12\x17.storage.DaoByIDRequest\x1a\x18.storage.DaoByIDResponseB\vZ\t.;storageb\x06proto3"

var (
	file_dao_proto_rawDescOnce sync.Once
	file_dao_proto_rawDescData []byte
)

func file_dao_proto_rawDescGZIP() []byte {
	file_dao_proto_rawDescOnce.Do(func() {
		file_dao_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dao_proto_rawDesc), len(file_dao_proto_rawDesc)))
	})
	return file_dao_proto_rawDescData
}

var file_dao_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dao_proto_goTypes = []any{
	(*DaoByIDRequest)(nil),        // 0: storage.DaoByIDRequest
	(*DaoInfo)(nil),               // 1: storage.DaoInfo
	(*DaoByIDResponse)(nil),       // 2: storage.DaoByIDResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_dao_proto_depIdxs = []int32{
	3, // 0: storage.DaoInfo.created_at:type_name -> google.protobuf.Timestamp
	3, // 1: storage.DaoInfo.updated_at:type_name -> google.protobuf.Timestamp
	1, // 2: storage.DaoByIDResponse.dao:type_name -> storage.DaoInfo
	0, // 3: storage.Dao.GetByID:input_type -> storage.DaoByIDRequest
	2, // 4: storage.Dao.GetByID:output_type -> storage.DaoByIDResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_dao_proto_init() }
func file_dao_proto_init() {
	if File_dao_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dao_proto_rawDesc), len(file_dao_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dao_proto_goTypes,
		DependencyIndexes: file_dao_proto_depIdxs,
		MessageInfos:      file_dao_proto_msgTypes,
	}.Build()
	File_dao_proto = out.File
	file_dao_proto_goTypes = nil
	file_dao_proto_depIdxs = nil
}
