// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proposal.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProposalInfoLevel int32

const (
	ProposalInfoLevel_PROPOSAL_INFO_LEVEL_UNSPECIFIED ProposalInfoLevel = 0
	ProposalInfoLevel_PROPOSAL_INFO_LEVEL_FULL        ProposalInfoLevel = 1
	ProposalInfoLevel_PROPOSAL_INFO_LEVEL_SHORT       ProposalInfoLevel = 2
)

// Enum value maps for ProposalInfoLevel.
var (
	ProposalInfoLevel_name = map[int32]string{
		0: "PROPOSAL_INFO_LEVEL_UNSPECIFIED",
		1: "PROPOSAL_INFO_LEVEL_FULL",
		2: "PROPOSAL_INFO_LEVEL_SHORT",
	}
	ProposalInfoLevel_value = map[string]int32{
		"PROPOSAL_INFO_LEVEL_UNSPECIFIED": 0,
		"PROPOSAL_INFO_LEVEL_FULL":        1,
		"PROPOSAL_INFO_LEVEL_SHORT":       2,
	}
)

func (x ProposalInfoLevel) Enum() *ProposalInfoLevel {
	p := new(ProposalInfoLevel)
	*p = x
	return p
}

func (x ProposalInfoLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProposalInfoLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_proposal_proto_enumTypes[0].Descriptor()
}

func (ProposalInfoLevel) Type() protoreflect.EnumType {
	return &file_proposal_proto_enumTypes[0]
}

func (x ProposalInfoLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProposalInfoLevel.Descriptor instead.
func (ProposalInfoLevel) EnumDescriptor() ([]byte, []int) {
	return file_proposal_proto_rawDescGZIP(), []int{0}
}

type ProposalByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalId    string                 `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposalByIDRequest) Reset() {
	*x = ProposalByIDRequest{}
	mi := &file_proposal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalByIDRequest) ProtoMessage() {}

func (x *ProposalByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proposal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalByIDRequest.ProtoReflect.Descriptor instead.
func (*ProposalByIDRequest) Descriptor() ([]byte, []int) {
	return file_proposal_proto_rawDescGZIP(), []int{0}
}

func (x *ProposalByIDRequest) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

type ProposalInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Author            string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	DaoId             string                 `protobuf:"bytes,5,opt,name=dao_id,json=daoId,proto3" json:"dao_id,omitempty"`
	Title             string                 `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	State             string                 `protobuf:"bytes,8,opt,name=state,proto3" json:"state,omitempty"`
	Type              string                 `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty"`
	Privacy           string                 `protobuf:"bytes,10,opt,name=privacy,proto3" json:"privacy,omitempty"`
	Spam              bool                   `protobuf:"varint,11,opt,name=spam,proto3" json:"spam,omitempty"`
	Timeline          []*Timeline            `protobuf:"bytes,12,rep,name=timeline,proto3" json:"timeline,omitempty"`
	Choices           []string               `protobuf:"bytes,13,rep,name=choices,proto3" json:"choices,omitempty"`
	OriginalCreatedAt *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=original_created_at,json=originalCreatedAt,proto3" json:"original_created_at,omitempty"`
	VotingStartedAt   *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=voting_started_at,json=votingStartedAt,proto3" json:"voting_started_at,omitempty"`
	VotingEndedAt     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=voting_ended_at,json=votingEndedAt,proto3" json:"voting_ended_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProposalInfo) Reset() {
	*x = ProposalInfo{}
	mi := &file_proposal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalInfo) ProtoMessage() {}

func (x *ProposalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proposal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalInfo.ProtoReflect.Descriptor instead.
func (*ProposalInfo) Descriptor() ([]byte, []int) {
	return file_proposal_proto_rawDescGZIP(), []int{1}
}

func (x *ProposalInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProposalInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProposalInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ProposalInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ProposalInfo) GetDaoId() string {
	if x != nil {
		return x.DaoId
	}
	return ""
}

func (x *ProposalInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProposalInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ProposalInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProposalInfo) GetPrivacy() string {
	if x != nil {
		return x.Privacy
	}
	return ""
}

func (x *ProposalInfo) GetSpam() bool {
	if x != nil {
		return x.Spam
	}
	return false
}

func (x *ProposalInfo) GetTimeline() []*Timeline {
	if x != nil {
		return x.Timeline
	}
	return nil
}

func (x *ProposalInfo) GetChoices() []string {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *ProposalInfo) GetOriginalCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OriginalCreatedAt
	}
	return nil
}

func (x *ProposalInfo) GetVotingStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VotingStartedAt
	}
	return nil
}

func (x *ProposalInfo) GetVotingEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VotingEndedAt
	}
	return nil
}

type Timeline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timeline) Reset() {
	*x = Timeline{}
	mi := &file_proposal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timeline) ProtoMessage() {}

func (x *Timeline) ProtoReflect() protoreflect.Message {
	mi := &file_proposal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timeline.ProtoReflect.Descriptor instead.
func (*Timeline) Descriptor() ([]byte, []int) {
	return file_proposal_proto_rawDescGZIP(), []int{2}
}

func (x *Timeline) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Timeline) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ProposalByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proposal      *ProposalInfo          `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposalByIDResponse) Reset() {
	*x = ProposalByIDResponse{}
	mi := &file_proposal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalByIDResponse) ProtoMessage() {}

func (x *ProposalByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proposal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalByIDResponse.ProtoReflect.Descriptor instead.
func (*ProposalByIDResponse) Descriptor() ([]byte, []int) {
	return file_proposal_proto_rawDescGZIP(), []int{3}
}

func (x *ProposalByIDResponse) GetProposal() *ProposalInfo {
	if x != nil {
		return x.Proposal
	}
	return nil
}

type ProposalByFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dao           *string                `protobuf:"bytes,1,opt,name=dao,proto3,oneof" json:"dao,omitempty"`
	Limit         *uint64                `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *uint64                `protobuf:"varint,3,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	ProposalIds   []string               `protobuf:"bytes,4,rep,name=proposal_ids,json=proposalIds,proto3" json:"proposal_ids,omitempty"`
	OnlyActive    *bool                  `protobuf:"varint,5,opt,name=only_active,json=onlyActive,proto3,oneof" json:"only_active,omitempty"`
	Level         *ProposalInfoLevel     `protobuf:"varint,6,opt,name=level,proto3,enum=storage.ProposalInfoLevel,oneof" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposalByFilterRequest) Reset() {
	*x = ProposalByFilterRequest{}
	mi := &file_proposal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalByFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalByFilterRequest) ProtoMessage() {}

func (x *ProposalByFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proposal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalByFilterRequest.ProtoReflect.Descriptor instead.
func (*ProposalByFilterRequest) Descriptor() ([]byte, []int) {
	return file_proposal_proto_rawDescGZIP(), []int{4}
}

func (x *ProposalByFilterRequest) GetDao() string {
	if x != nil && x.Dao != nil {
		return *x.Dao
	}
	return ""
}

func (x *ProposalByFilterRequest) GetLimit() uint64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ProposalByFilterRequest) GetOffset() uint64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *ProposalByFilterRequest) GetProposalIds() []string {
	if x != nil {
		return x.ProposalIds
	}
	return nil
}

func (x *ProposalByFilterRequest) GetOnlyActive() bool {
	if x != nil && x.OnlyActive != nil {
		return *x.OnlyActive
	}
	return false
}

func (x *ProposalByFilterRequest) GetLevel() ProposalInfoLevel {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return ProposalInfoLevel_PROPOSAL_INFO_LEVEL_UNSPECIFIED
}

type ProposalByFilterResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Proposals      []*ProposalInfo        `protobuf:"bytes,1,rep,name=proposals,proto3" json:"proposals,omitempty"`
	TotalCount     uint64                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	ProposalsShort []*ProposalShortInfo   `protobuf:"bytes,3,rep,name=proposals_short,json=proposalsShort,proto3" json:"proposals_short,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProposalByFilterResponse) Reset() {
	*x = ProposalByFilterResponse{}
	mi := &file_proposal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalByFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalByFilterResponse) ProtoMessage() {}

func (x *ProposalByFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proposal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalByFilterResponse.ProtoReflect.Descriptor instead.
func (*ProposalByFilterResponse) Descriptor() ([]byte, []int) {
	return file_proposal_proto_rawDescGZIP(), []int{5}
}

func (x *ProposalByFilterResponse) GetProposals() []*ProposalInfo {
	if x != nil {
		return x.Proposals
	}
	return nil
}

func (x *ProposalByFilterResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ProposalByFilterResponse) GetProposalsShort() []*ProposalShortInfo {
	if x != nil {
		return x.ProposalsShort
	}
	return nil
}

type ProposalShortInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Created       uint64                 `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposalShortInfo) Reset() {
	*x = ProposalShortInfo{}
	mi := &file_proposal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalShortInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalShortInfo) ProtoMessage() {}

func (x *ProposalShortInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proposal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalShortInfo.ProtoReflect.Descriptor instead.
func (*ProposalShortInfo) Descriptor() ([]byte, []int) {
	return file_proposal_proto_rawDescGZIP(), []int{6}
}

func (x *ProposalShortInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProposalShortInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProposalShortInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ProposalShortInfo) GetCreated() uint64 {
	if x != nil {
		return x.Created
	}
	return 0
}

var File_proposal_proto protoreflect.FileDescriptor

const file_proposal_proto_rawDesc = "" +
	"\n" +
	"\x0eproposal.proto\x12\astorage\x1a\x1fgoogle/protobuf/timestamp.proto\"6\n" +
	"\x13ProposalByIDRequest\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\tR\n" +
	"proposalId\"\xd2\x04\n" +
	"\fProposalInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x15\n" +
	"\x06dao_id\x18\x05 \x01(\tR\x05daoId\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12\x14\n" +
	"\x05state\x18\b \x01(\tR\x05state\x12\x12\n" +
	"\x04type\x18\t \x01(\tR\x04type\x12\x18\n" +
	"\aprivacy\x18\n" +
	" \x01(\tR\aprivacy\x12\x12\n" +
	"\x04spam\x18\v \x01(\bR\x04spam\x12-\n" +
	"\btimeline\x18\f \x03(\v2\x11.storage.TimelineR\btimeline\x12\x18\n" +
	"\achoices\x18\r \x03(\tR\achoices\x12J\n" +
	"\x13original_created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\x11originalCreatedAt\x12F\n" +
	"\x11voting_started_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\x0fvotingStartedAt\x12B\n" +
	"\x0fvoting_ended_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\rvotingEndedAt\"]\n" +
	"\bTimeline\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"I\n" +
	"\x14ProposalByIDResponse\x121\n" +
	"\bproposal\x18\x01 \x01(\v2\x15.storage.ProposalInfoR\bproposal\"\x9f\x02\n" +
	"\x17ProposalByFilterRequest\x12\x15\n" +
	"\x03dao\x18\x01 \x01(\tH\x00R\x03dao\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x04H\x01R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x03 \x01(\x04H\x02R\x06offset\x88\x01\x01\x12!\n" +
	"\fproposal_ids\x18\x04 \x03(\tR\vproposalIds\x12$\n" +
	"\vonly_active\x18\x05 \x01(\bH\x03R\n" +
	"onlyActive\x88\x01\x01\x125\n" +
	"\x05level\x18\x06 \x01(\x0e2\x1a.storage.ProposalInfoLevelH\x04R\x05level\x88\x01\x01B\x06\n" +
	"\x04_daoB\b\n" +
	"\x06_limitB\t\n" +
	"\a_offsetB\x0e\n" +
	"\f_only_activeB\b\n" +
	"\x06_level\"\xb5\x01\n" +
	"\x18ProposalByFilterResponse\x123\n" +
	"\tproposals\x18\x01 \x03(\v2\x15.storage.ProposalInfoR\tproposals\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x04R\n" +
	"totalCount\x12C\n" +
	"\x0fproposals_short\x18\x03 \x03(\v2\x1a.storage.ProposalShortInfoR\x0eproposalsShort\"i\n" +
	"\x11ProposalShortInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x18\n" +
	"\acreated\x18\x04 \x01(\x04R\acreated*u\n" +
	"\x11ProposalInfoLevel\x12#\n" +
	"\x1fPROPOSAL_INFO_LEVEL_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18PROPOSAL_INFO_LEVEL_FULL\x10\x01\x12\x1d\n" +
	"\x19PROPOSAL_INFO_LEVEL_SHORT\x10\x022\xa6\x01\n" +
	"\bProposal\x12F\n" +
	"\aGetByID\x12\x1c.storage.ProposalByIDRequest\x1a\x1d.storage.ProposalByIDResponse\x12R\n" +
	"\vGetByFilter\x12 .storage.ProposalByFilterRequest\x1a!.storage.ProposalByFilterResponseB\vZ\t.;storageb\x06proto3"

var (
	file_proposal_proto_rawDescOnce sync.Once
	file_proposal_proto_rawDescData []byte
)

func file_proposal_proto_rawDescGZIP() []byte {
	file_proposal_proto_rawDescOnce.Do(func() {
		file_proposal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proposal_proto_rawDesc), len(file_proposal_proto_rawDesc)))
	})
	return file_proposal_proto_rawDescData
}

var file_proposal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proposal_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proposal_proto_goTypes = []any{
	(ProposalInfoLevel)(0),           // 0: storage.ProposalInfoLevel
	(*ProposalByIDRequest)(nil),      // 1: storage.ProposalByIDRequest
	(*ProposalInfo)(nil),             // 2: storage.ProposalInfo
	(*Timeline)(nil),                 // 3: storage.Timeline
	(*ProposalByIDResponse)(nil),     // 4: storage.ProposalByIDResponse
	(*ProposalByFilterRequest)(nil),  // 5: storage.ProposalByFilterRequest
	(*ProposalByFilterResponse)(nil), // 6: storage.ProposalByFilterResponse
	(*ProposalShortInfo)(nil),        // 7: storage.ProposalShortInfo
	(*timestamppb.Timestamp)(nil),    // 8: google.protobuf.Timestamp
}
var file_proposal_proto_depIdxs = []int32{
	8,  // 0: storage.ProposalInfo.created_at:type_name -> google.protobuf.Timestamp
	8,  // 1: storage.ProposalInfo.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 2: storage.ProposalInfo.timeline:type_name -> storage.Timeline
	8,  // 3: storage.ProposalInfo.original_created_at:type_name -> google.protobuf.Timestamp
	8,  // 4: storage.ProposalInfo.voting_started_at:type_name -> google.protobuf.Timestamp
	8,  // 5: storage.ProposalInfo.voting_ended_at:type_name -> google.protobuf.Timestamp
	8,  // 6: storage.Timeline.created_at:type_name -> google.protobuf.Timestamp
	2,  // 7: storage.ProposalByIDResponse.proposal:type_name -> storage.ProposalInfo
	0,  // 8: storage.ProposalByFilterRequest.level:type_name -> storage.ProposalInfoLevel
	2,  // 9: storage.ProposalByFilterResponse.proposals:type_name -> storage.ProposalInfo
	7,  // 10: storage.ProposalByFilterResponse.proposals_short:type_name -> storage.ProposalShortInfo
	1,  // 11: storage.Proposal.GetByID:input_type -> storage.ProposalByIDRequest
	5,  // 12: storage.Proposal.GetByFilter:input_type -> storage.ProposalByFilterRequest
	4,  // 13: storage.Proposal.GetByID:output_type -> storage.ProposalByIDResponse
	6,  // 14: storage.Proposal.GetByFilter:output_type -> storage.ProposalByFilterResponse
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proposal_proto_init() }
func file_proposal_proto_init() {
	if File_proposal_proto != nil {
		return
	}
	file_proposal_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proposal_proto_rawDesc), len(file_proposal_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proposal_proto_goTypes,
		DependencyIndexes: file_proposal_proto_depIdxs,
		EnumInfos:         file_proposal_proto_enumTypes,
		MessageInfos:      file_proposal_proto_msgTypes,
	}.Build()
	File_proposal_proto = out.File
	file_proposal_proto_goTypes = nil
	file_proposal_proto_depIdxs = nil
}
